### PR TITLE
Developer Options

### PR DESCRIPTION
**Pull request by cube-m4st3r**
# Problem: Data insertion of new values
Insertion of new data into the database is very complicated via. the terminal.

### Solution:
Discord command based insertion via. select menus, modals 

### Listings
- [x] Enemy insertion
- [x] Confirmation
- Database functions 
- [x] functional
- [x] insertion enemy_moves
- [x] insertion encounter 
- [x] insertion of quests
 
```python
version="1.0"
print(f"Current version: {version}")
```

### CODE REVIEW

**Comment by cube-m4st3r** [comment]
## Little FAQ
### I also asked myself: why not work with classes?
I decided to not work OOP/with classes to avoid _potential_ data trash. 
That's why I've been using/creating new functions for the commands inside db.py to work-around the classes already existing.

### Is it possible to adjust the code to work with classes easily in the future?
Absolutely! I always aim to make my code as dynamic as possible (to my knowledge that is)

```python
await interaction.response.send_message(content="More updates to come!")
```

**Comment by cube-m4st3r** [comment]
4c18295:
- [x] locationselect works with encounter and enemy
- [x] created instertencounter button
- [x] created encounter modal
- [ ] insertion to database

```python
print("Onto another commit!")
```

**Comment by cube-m4st3r** [comment]
3c0ce39:
- [x] enemy_moves button, modal and selections
- [ ] insertion to database

```python
print("Move forward.")
```

**Comment by cube-m4st3r** [comment]
### Save DB Insertions via. SQL Statements within a .JSON file
- [ ] add SQL statement
- [ ] button to read JSON file
- [ ] remove SQL statement
- [ ] update SQL statement
- [ ] give the entries an ID for better sourcing

**Comment by cube-m4st3r** [comment]
### Quest insertion
finished inserting quests, missing the quest_has_item table and some exceptions e.g. "none"

**Comment by JanikCodes** [comment]
LGTM

**Pull request merged**
